global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'TRI-SB-LAX-N1-01'
    static_configs:
      - targets: ['72.5.46.63:9040']
        labels:
          instance: 'TRI-SB-LAX-N1-01'

  - job_name: 'TRI-PRX-LAX-N1-01'
    static_configs:
      - targets: ['72.5.46.63:9041']
        labels:
          instance: 'TRI-PRX-LAX-N1-01'

  - job_name: 'TRI-MN-LAX-N1-01'
    static_configs:
      - targets: ['72.5.46.63:9042']
        labels:
          instance: 'TRI-MN-LAX-N1-01'          

  - job_name: 'TRI-LBB-LAX-N1-01'
    static_configs:
      - targets: ['72.5.46.63:9043']
        labels:
          instance: 'TRI-LBB-LAX-N1-01'

  - job_name: 'TRI-CRE-LAX-N1-01'
    static_configs:
      - targets: ['72.5.46.63:9044']
        labels:
          instance: 'TRI-CRE-LAX-N1-01'          

  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']

  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE
